import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Dominic DiCocco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-10 flex justify-between'>
            <h1 className='text-xl font-burtons'>DevelopedByJulio</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Dominic DiCocco</h2>
            <h3 className='text-2xl py-2'>Developer and Designer</h3>
            <p className='text-medium py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>Freelancer providing services for programing and design content needs.
              Join me down bellow and let's get cracking!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} alt='hero' layout='fill' objectFit='cover' />
          </div>
        </section>
        <section>
          <h3 className='text-3xl py-1'>Services I offer</h3>
          <p className='text-md py-2 leading-8 text-gray-800'>
            Since the beginning of my journey as a freelance designer and developer, I've done remote work for 
            <span className='text-teal-500'> agencies </span>
            consulted for <span className='text-teal-500'> startups </span>
            and collaborated with talented people to create digital products for
            both bussiness and consumer use.
          </p>
          <p className='text-md py-2 leading-8 text-gray-800'>
            I offer from a wide range of services, including brand design, programming, and teaching.
          </p>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} alt='' width={100} height={100} />
              <h3 className='text-lg font-medium pb-2 pt-8'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className='py-4 text-teal-600'>Desing tools I use.</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} alt='' width={100} height={100} />
              <h3 className='text-lg font-medium pb-2 pt-8'>Elegant Code</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className='py-4 text-teal-600'>Desing tools I use.</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={consulting} alt='' width={100} height={100} />
              <h3 className='text-lg font-medium pb-2 pt-8'>Great Consulting</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className='py-4 text-teal-600'>Desing tools I use.</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Since the beginning of my journey as a freelance designer and developer, I've done remote work for 
              <span className='text-teal-500'> agencies </span>
              consulted for <span className='text-teal-500'> startups </span>
              and collaborated with talented people to create digital products for
              both bussiness and consumer use.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800'>
              I offer from a wide range of services, including brand design, programming, and teaching.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} alt='' className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} alt='' className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} alt='' className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} alt='' className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} alt='' className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} alt='' className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
          </div>

        </section>
      </main>

    </div>
  )
}
